### PR TITLE
Maybe fix unreponsive controller after wakeup finally

### LINKED ISSUE #36: Controller Unresponsive on Wake from Suspend (Bazzite)
After waking the system from sleep the controller successfully connects to the dongle but is unresponsive in Steam. Since usbreset is not included in the Bazzite image it's not a feasible workaround for Bazzite. To fix, the dongle needs to be unplugged but only after turning the controller off first. That or a system reboot. [Full dmesg log here](https://github.com/user-attachments/files/19054183/dmesg.log), [Current boot log here](https://github.com/user-attachments/files/19054203/boot.log).

Hardware/System: 
1. Xbox Elite 2 (Latest Firmware) connected via the Xbox Wireless Adapter (Unknown Firmware).
2. Bazzite 41 (FROM Fedora Kinoite); Linux 6.13.5-100.bazzite.fc41.x86_64

Repro Steps:
1.  In Steam game mode via the controller put the system to sleep
2. Wake the system from sleep via the Xbox button (back into Steam game mode)

### LINKED ISSUE #132: Controller input device fails to register after resume
I believe commit #118 introduced a regression, there is a race condition on resume where the controller may not fully register the input device. 

If I wake the system from sleep using the gamepad, the input device is never registered by the xone driver.
However, if I wake the system another way (power button, keyboard, etc) and turn on the controller after the system has resumed, the input device is properly registered and the controller functions has expected.

[dmesg_failure.txt](https://github.com/user-attachments/files/23397665/dmesg_failure.txt)

Initial successful connection of gamepad:
```
[  226.729305] input: Microsoft Xbox Controller as /devices/pci0000:00/0000:00:08.1/0000:0d:00.4/usb5/5-2/5-2:1.0/gip0/gip0.0/input/input32
[  226.729401] xone-gip-gamepad gip0.0: gip_register_client: registered
....
[  227.266083] xone-gip gip0: gip_send_pkt_simple: cmd=0x06 len=0x0006 seq=0x0e offset=0x0000
[  227.281417] xone_dongle_handle_event: XONE_DONGLE_EVT_ENABLE_ENCRYPTION
[  227.281422] xone-dongle 5-2:1.0: xone_dongle_enable_client_encryption: wcid=1, address=7e:ed:83:25:08:49
[  228.262114] input: Microsoft X-Box 360 pad 0 as /devices/virtual/input/input33
```

After resume note missing "input: Microsoft X-Box 360 pad 0"
```
[  239.580169] input: Microsoft Xbox Controller as /devices/pci0000:00/0000:00:08.1/0000:0d:00.4/usb5/5-2/5-2:1.0/gip0/gip0.0/input/input34
...
[  240.111689] xone_dongle_handle_event: XONE_DONGLE_EVT_ENABLE_ENCRYPTION
[  240.111695] xone-dongle 5-2:1.0: xone_dongle_enable_client_encryption: wcid=1, address=7e:ed:83:25:08:49
```

I've tested reverting #118 and have confirmed this resolves the issue.

[dmesg_118_reverted_fixed.txt](https://github.com/user-attachments/files/23397881/dmesg_118_reverted_fixed.txt)

@Lawstorant Its not clear to me why the gip_gamepad_init_input() call was moved by this change, could you explain the reason for this? Can #118 be reverted/fixed? Thanks!

### PR DESCRIPTION
**Pull request by Lawstorant**
Fixes #132
Fixes #36

### CODE REVIEW

File: bus/bus.c [hunk 1]
```diff
@@ -243,6 +244,18 @@ static void gip_register_client(struct work_struct *work)
 						 work_register);
 	int err;
 
+	/*
+	 * Sometimes, after wakeup from sleep gamepads are unresponsive, Turns
+	 * out, it has to do something with how fast this function is performed.
+	 * Our best guess for now is that some kind of data is just not getting
+	 * there fast enough with some hubs that loose power and some timeouts
```
Comment (andyschmid) [inline bus/bus.c]: Typo in comment, "lose power"*

File: transport/dongle.c [hunk 2]
```diff
@@ -1186,6 +1186,7 @@ static int xone_dongle_resume(struct usb_interface *intf)
 		return 0;
 	}
 
+	msleep(500);
```
Comment (andyschmid) [inline transport/dongle.c]: This delay was not necessary in my testing

**Review by andyschmid — APPROVED** [review]
