### PR TITLE
Fix snprintf call warning/error

### LINKED ISSUE #63: Build error on linux-6.12.31-gentoo
Build fails on Gentoo with kernel 6.12.31:

```
❯ doas ./install.sh
Installing xone unknown...
The kernel is built without module signing facility, modules won't be signed

Creating symlink /var/lib/dkms/xone/unknown/source -> /usr/src/xone-unknown

Cleaning build area... done.
Building module(s)...(bad exit status: 2)
Failed command:
make -j24 KERNELRELEASE=6.12.31-gentoo -C /lib/modules/6.12.31-gentoo/build M=/var/lib/dkms/xone/unknown/build

Error! Bad return status for module build on kernel: 6.12.31-gentoo (x86_64)
Consult /var/lib/dkms/xone/unknown/build/make.log for more information.
DKMS (dkms-3.1.6) make.log for xone/unknown for kernel 6.12.31-gentoo (x86_64)
Mon Jun  9 22:42:29 CEST 2025

Cleaning build area
# command: make -C /lib/modules/6.12.31-gentoo/build M=/var/lib/dkms/xone/unknown/build clean
make: Entering directory '/usr/src/linux-6.12.31-gentoo'
make: Leaving directory '/usr/src/linux-6.12.31-gentoo'

# exit code: 0
# elapsed time: 00:00:00
----------------------------------------------------------------

Building module(s)
# command: make -j24 KERNELRELEASE=6.12.31-gentoo -C /lib/modules/6.12.31-gentoo/build M=/var/lib/dkms/xone/unknown/build
make: Entering directory '/usr/src/linux-6.12.31-gentoo'
  CC [M]  /var/lib/dkms/xone/unknown/build/transport/wired.o
  CC [M]  /var/lib/dkms/xone/unknown/build/transport/dongle.o
  CC [M]  /var/lib/dkms/xone/unknown/build/transport/mt76.o
  CC [M]  /var/lib/dkms/xone/unknown/build/bus/bus.o
  CC [M]  /var/lib/dkms/xone/unknown/build/bus/protocol.o
  CC [M]  /var/lib/dkms/xone/unknown/build/auth/auth.o
  CC [M]  /var/lib/dkms/xone/unknown/build/auth/crypto.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/common.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/gamepad.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/headset.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/chatpad.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/madcatz_strat.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/madcatz_glam.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/pdp_jaguar.o
  LD [M]  /var/lib/dkms/xone/unknown/build/xone-gip-gamepad.o
  LD [M]  /var/lib/dkms/xone/unknown/build/xone-gip-madcatz-strat.o
  LD [M]  /var/lib/dkms/xone/unknown/build/xone-gip-chatpad.o
  LD [M]  /var/lib/dkms/xone/unknown/build/xone-gip-headset.o
  LD [M]  /var/lib/dkms/xone/unknown/build/xone-gip-madcatz-glam.o
/var/lib/dkms/xone/unknown/build/transport/dongle.c: In function 'xone_dongle_init':
/var/lib/dkms/xone/unknown/build/transport/dongle.c:892:46: error: too many arguments for format [-Werror=format-extra-args]
  892 |                         snprintf(fwname, 25, "xow_dongle.bin",
      |                                              ^~~~~~~~~~~~~~~~
  LD [M]  /var/lib/dkms/xone/unknown/build/xone-gip-pdp-jaguar.o
  LD [M]  /var/lib/dkms/xone/unknown/build/xone-wired.o
  LD [M]  /var/lib/dkms/xone/unknown/build/xone-gip.o
cc1: all warnings being treated as errors
make[2]: *** [scripts/Makefile.build:229: /var/lib/dkms/xone/unknown/build/transport/dongle.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/usr/src/linux-6.12.31-gentoo/Makefile:1947: /var/lib/dkms/xone/unknown/build] Error 2
make: *** [Makefile:224: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-6.12.31-gentoo'

# exit code: 2
# elapsed time: 00:00:01
----------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by Lawstorant**
```
transport/dongle.c: In function ‘xone_dongle_init’:
transport/dongle.c:892:46: warning: too many arguments for format [-Wformat-extra-args]
  892 |                         snprintf(fwname, 25, "xow_dongle.bin",
      |                                              ^~~~~~~~~~~~~~~~
```

Fixes #63

### CODE REVIEW

File: transport/dongle.c [hunk 1]
```diff
@@ -888,8 +888,7 @@ static int xone_dongle_init(struct xone_dongle *dongle,
 			__func__, fwname);
 	err = request_firmware(&fw, fwname, mt->dev);
 	if (err == -ENOENT) {
-		snprintf(fwname, 25, "xow_dongle.bin",
-				id->idVendor, id->idProduct);
+		snprintf(fwname, 15, "xow_dongle.bin");
```
Comment (dlundqvist) [inline transport/dongle.c:891]: Rookie mistake from me! :)

**Comment by dlundqvist** [comment]
Thanks for fixing this.
